[[plugins]]
repo = 'Shougo/dein.vim'

# colorscheme hybrid
[[plugins]]
repo = 'w0ng/vim-hybrid'

# Transparent netrw cursor line
[[plugins]]
repo = 'vim-scripts/netrw.vim'

# Used by statusline
[[plugins]]
repo = 'tpope/vim-fugitive'
