#===============================================================================
# Language
#===============================================================================
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#===============================================================================
# Denite
#===============================================================================
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = ['Denite']
hook_source = 'source ~/.config/nvim/rc/denite.vim'
hook_post_source = '''
  call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')
'''
