#===============================================================================
# Language
#===============================================================================
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#===============================================================================
# Unite
#===============================================================================
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite']
depends = ['vimproc.vim']
hook_post_source = '''
  autocmd FileType unite highlight CursorLine cterm=reverse
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
