#===============================================================================
# Dein
#===============================================================================
[[plugins]]
repo = 'Shougo/dein.vim'

#===============================================================================
# Styles
#===============================================================================
[[plugins]] # colorscheme hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # Transparent netrw cursor line
repo = 'vim-scripts/netrw.vim'

#===============================================================================
# Git
#===============================================================================
[[plugins]] # Used by statusline
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
