[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# colorscheme hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]]
# Make a current cursor transparent
repo = 'vim-scripts/netrw.vim'

[[plugins]]
# Used by statusline
repo = 'tpope/vim-fugitive'
