#===============================================================================
# Language
#===============================================================================
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#===============================================================================
# Unite
#===============================================================================
[[plugins]]
repo = 'k0kubun/unite.vim'
on_cmd = ['Unite']
depends = ['vimproc.vim']
hook_post_source = '''
  autocmd BufEnter,BufWinEnter \[unite\]* highlight! CursorLine ctermfg=Black ctermbg=Grey
  autocmd BufLeave \[unite\]* highlight! CursorLine ctermfg=NONE ctermbg=NONE
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
