#===============================================================================
# Language
#===============================================================================
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#===============================================================================
# Completion
#===============================================================================
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1

  " Select the first line by default
  set completeopt+=noinsert

  if has('mac')
    " brew install python
    " /usr/local/bin/pip3 install pynvim
    " :UpdateRemotePlugins
    let g:python3_host_prog = '/usr/local/bin/python3'
  else
    let g:python3_host_prog = '/usr/bin/python3'
  endif
'''

#===============================================================================
# Unite
#===============================================================================
[[plugins]]
repo = 'k0kubun/unite.vim'
on_cmd = ['Unite']
depends = ['vimproc.vim']
hook_post_source = '''
  autocmd BufEnter,BufWinEnter \[unite\]* highlight! CursorLine ctermfg=Black ctermbg=Grey
  autocmd BufLeave \[unite\]* highlight! CursorLine ctermfg=NONE ctermbg=NONE
'''

[[plugins]]
repo = 'k0kubun/unite-git_files'
on_cmd = ['Unite']
depends = ['unite.vim']

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

#===============================================================================
# Git
#===============================================================================
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_post_source = '''
  delfunction OpenBrowser
  delcommand OpenBrowser
  delfunction OpenBrowserSearch
  delcommand OpenBrowserSearch
  delcommand OpenBrowserSmartSearch
'''

[[plugins]]
repo = 'k0kubun/open-browser-github.vim'
on_cmd = ['OpenGithubFile']
depends = ['open-browser.vim']
hook_post_source = '''
  delcommand OpenGithubCommit
  delcommand OpenGithubIssue
  delcommand OpenGithubProject
  delcommand OpenGithubPullReq
'''
