#===============================================================================
# SKK
#===============================================================================
[[plugins]]
repo = 'tyru/skk.vim'

[[plugins]]
repo = 'tyru/skkdict.vim'
