#===============================================================================
# Language
#===============================================================================
[[plugins]]
repo = 'mrkn/vim-cruby'
on_ft = ['cruby']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#===============================================================================
# Editing
#===============================================================================
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
# on_if = 'has("python3")'
on_if = 'has("nvim")'
hook_source = '''
  let g:deoplete#enable_at_startup = 1

  " Select the first line by default
  set completeopt+=noinsert
'''

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = ['OverCommandLine']

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_cmd = ['FixWhitespace']

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise']

#===============================================================================
# Unite
#===============================================================================
[[plugins]]
repo = 'k0kubun/unite.vim'
on_cmd = ['Unite']
depends = ['vimproc.vim', 'unite-git_files']
hook_post_source = '''
  autocmd BufEnter,BufWinEnter \[unite\]* highlight! CursorLine ctermfg=Black ctermbg=Grey
  autocmd BufLeave \[unite\]* highlight! CursorLine ctermfg=NONE ctermbg=NONE
'''

[[plugins]]
repo = 'k0kubun/unite-git_files'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

#===============================================================================
# Git
#===============================================================================
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_post_source = '''
  delfunction OpenBrowser
  delcommand OpenBrowser
  delfunction OpenBrowserSearch
  delcommand OpenBrowserSearch
  delcommand OpenBrowserSmartSearch
'''

[[plugins]]
repo = 'k0kubun/open-browser-github.vim'
on_cmd = ['OpenGithubFile']
depends = ['open-browser.vim']
hook_source = '''
  let g:openbrowser_github_select_current_line = 1
  let g:openbrowser_github_url_exists_check = 'ignore'
'''
hook_post_source = '''
  delcommand OpenGithubCommit
  delcommand OpenGithubIssue
  delcommand OpenGithubProject
  delcommand OpenGithubPullReq
'''
