#===============================================================================
# Language
#===============================================================================
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#===============================================================================
# Completion
#===============================================================================
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
  " Select the first line by default
  set completeopt+=noinsert
  let g:python3_host_prog = '/usr/bin/python3'
  let g:deoplete#enable_at_startup = 1
'''

#===============================================================================
# Unite
#===============================================================================
[[plugins]]
repo = 'k0kubun/unite.vim'
on_cmd = ['Unite']
depends = ['vimproc.vim']
hook_post_source = '''
  autocmd BufEnter,BufWinEnter \[unite\]* highlight! CursorLine ctermfg=Black ctermbg=Grey
  autocmd BufLeave \[unite\]* highlight! CursorLine ctermfg=NONE ctermbg=NONE
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
