#===============================================================================
# Dein
#===============================================================================
[[plugins]]
repo = 'Shougo/dein.vim'
# :call dein#recache_runtimepath()

#===============================================================================
# Styles
#===============================================================================
[[plugins]] # colorscheme hybrid
repo = 'w0ng/vim-hybrid'

#===============================================================================
# Git
#===============================================================================
[[plugins]] # Used by statusline
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#===============================================================================
# SKK
#===============================================================================
[[plugins]]
repo = 'tyru/eskk.vim'
on_if = 'has("mac") && !exists("g:vscode")'
hook_source = '''
  let g:eskk#large_dictionary = {'path': "~/Library/Application Support/AquaSKK/SKK-JISYO.L", 'sorted': 1, 'encoding': 'euc-jp'}
'''
