#===============================================================================
# Language
#===============================================================================
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = '''
  let g:vimtex_matchparen_enabled = 0
'''
# apt install latexmk

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescriptreact']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

#===============================================================================
# Editing
#===============================================================================
[[plugins]]
repo = 'neoclide/coc.nvim'
rev  = 'v0.0.81'
on_i = 1

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = ['OverCommandLine']

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_cmd = ['FixWhitespace']

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise']

#===============================================================================
# Unite
#===============================================================================
[[plugins]]
repo = 'k0kubun/unite.vim'
on_cmd = ['Unite']
depends = ['vimproc.vim', 'unite-git_files']
hook_post_source = '''
  autocmd BufEnter,BufWinEnter \[unite\]* highlight! CursorLine ctermfg=Black ctermbg=Grey
  autocmd BufLeave \[unite\]* highlight! CursorLine ctermfg=NONE ctermbg=NONE
'''

[[plugins]]
repo = 'k0kubun/unite-git_files'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

#===============================================================================
# Git
#===============================================================================
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_post_source = '''
  delfunction OpenBrowser
  delcommand OpenBrowser
  delfunction OpenBrowserSearch
  delcommand OpenBrowserSearch
  delcommand OpenBrowserSmartSearch
'''

[[plugins]]
repo = 'k0kubun/open-browser-github.vim'
on_cmd = ['OpenGithubFile']
depends = ['open-browser.vim']
hook_source = '''
  let g:openbrowser_github_select_current_line = 1
  let g:openbrowser_github_url_exists_check = 'ignore'
'''
hook_post_source = '''
  delcommand OpenGithubCommit
  delcommand OpenGithubIssue
  delcommand OpenGithubProject
  delcommand OpenGithubPullReq
'''
