include_cookbook 'dotfiles'
include_cookbook 'git'
include_cookbook 'vim'

dotfile '.peco'
dotfile '.rake'
dotfile '.zsh'

dotfile '.Xdefaults'
dotfile '.gemrc'
dotfile '.gtkrc-2.0'
dotfile '.pryrc'
dotfile '.railsrc'
dotfile '.rbindkeys'
dotfile '.tmux.conf'
dotfile '.xinitrc'
dotfile '.zshrc'
