dotfile '.config/nvim/coc-settings.json'
dotfile '.config/nvim/init.vim'
dotfile '.gitconfig'
dotfile '.peco'
dotfile '.tmux.conf'
dotfile '.tmux.conf.local' => '.tmux.conf.linux'
dotfile '.zsh'
dotfile '.zshrc'
dotfile '.zshrc.Linux'

package 'tmux'
package 'zsh'
package 'htop'

include_recipe 'zsh'
include_recipe 'neovim'
include_recipe 'systemd'
include_recipe 'ssh-agent'
